# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - 7070:7070
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_USER: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  node:
    build: .
    restart: always
    command: npm start 
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    
  